# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dts', models.DateTimeField()),
                ('counter', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
            ],
        ),
    ]
