# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
