# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescores', '0002_auto_20170103_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsevent',
            name='lsid',
            field=models.IntegerField(unique=True),
        ),
    ]
