# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BFChamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfid', models.IntegerField()),
                ('lid', models.IntegerField(null=True)),
                ('sport', models.IntegerField()),
                ('country_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BFEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfid', models.IntegerField()),
                ('lid', models.IntegerField(null=True)),
                ('rid1', models.IntegerField()),
                ('rid2', models.IntegerField()),
                ('dt', models.DateTimeField()),
                ('dtc', models.DateTimeField(null=True)),
                ('dtip', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair_app.BFChamp')),
            ],
        ),
        migrations.CreateModel(
            name='BFOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1odds', models.FloatField()),
                ('b2odds', models.FloatField()),
                ('b1size', models.FloatField()),
                ('b2size', models.FloatField()),
                ('dtc', models.DateTimeField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair_app.BFEvent')),
            ],
        ),
        migrations.CreateModel(
            name='BFPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bfevent',
            name='pid1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='betfair_app.BFPlayer'),
        ),
        migrations.AddField(
            model_name='bfevent',
            name='pid2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='betfair_app.BFPlayer'),
        ),
    ]
