# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bfodds',
            name='l1odds',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bfodds',
            name='l1size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bfodds',
            name='l2odds',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bfodds',
            name='l2size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
