# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_app', '0002_auto_20170102_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfchamp',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
