# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_app', '0005_auto_20170102_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfodds',
            name='b1size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bfodds',
            name='b2size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bfodds',
            name='dtc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bfodds',
            name='l1size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bfodds',
            name='l2size',
            field=models.FloatField(null=True),
        ),
    ]
