# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_app', '0007_bfodds_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfchamp',
            name='lid',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='dt',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='dtc',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='lid',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bfodds',
            name='dtc',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bfplayer',
            name='lid',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bfplayer',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
