# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('champ', models.CharField(max_length=100)),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('w1', models.FloatField(null=True)),
                ('w2', models.FloatField(null=True)),
                ('w1max', models.FloatField(null=True)),
                ('w2max', models.FloatField(null=True)),
                ('gender', models.IntegerField()),
                ('sets1', models.IntegerField(null=True)),
                ('sets2', models.IntegerField(null=True)),
                ('dt', models.DateTimeField(null=True)),
                ('dtadd', models.DateTimeField(null=True)),
                ('result', models.IntegerField(null=True)),
            ],
        ),
    ]
