# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddsportal', '0002_auto_20170213_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opodds',
            old_name='event',
            new_name='ev',
        ),
    ]
