# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsgame',
            name='prewin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lsplayer',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
