# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescores', '0003_auto_20170105_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsgame',
            name='serve',
            field=models.IntegerField(null=True),
        ),
    ]
