# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescores', '0004_lsgame_serve'),
    ]

    operations = [
        migrations.AddField(
            model_name='lschamp',
            name='mcid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lsevent',
            name='meid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lsplayer',
            name='mpid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lsevent',
            name='dtc',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lsgame',
            name='dtc',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lsplayer',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
