# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170102_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
