# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MChamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcid', models.IntegerField(null=True)),
                ('sport', models.IntegerField(null=True)),
                ('countryid', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('prize', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('surface', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meid', models.IntegerField(null=True)),
                ('dt', models.DateTimeField(db_index=True, null=True)),
                ('mcid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sposta_app.MChamp')),
            ],
        ),
        migrations.CreateModel(
            name='MPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpid', models.IntegerField(null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mevent',
            name='mpid1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mplayer1', to='sposta_app.MPlayer'),
        ),
        migrations.AddField(
            model_name='mevent',
            name='mpid2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mplayer2', to='sposta_app.MPlayer'),
        ),
    ]
