# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sposta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchamp',
            name='countryid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mchamp',
            name='mcid',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mevent',
            name='meid',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mplayer',
            name='mpid',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
