# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sposta_app', '0002_mevent_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc', models.IntegerField(db_index=True)),
                ('meid', models.IntegerField(db_index=True)),
                ('pid', models.IntegerField(db_index=True)),
                ('tp', models.IntegerField()),
                ('tw', models.IntegerField()),
                ('s1w', models.IntegerField()),
                ('s1ws2l', models.IntegerField()),
                ('s1wml', models.IntegerField()),
                ('s1ws2lmw', models.IntegerField()),
                ('s1l', models.IntegerField()),
                ('s1ls2w', models.IntegerField()),
                ('s1lmw', models.IntegerField()),
                ('s1ls2wml', models.IntegerField()),
            ],
        ),
    ]
