# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sposta_app', '0002_auto_20170207_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mevent',
            old_name='mcid',
            new_name='champ',
        ),
        migrations.RenameField(
            model_name='mevent',
            old_name='mpid1',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='mevent',
            old_name='mpid2',
            new_name='p2',
        ),
    ]
