# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sposta_app', '0003_auto_20170209_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mevent',
            name='res',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mplayer',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mplayer',
            name='db',
            field=models.DateTimeField(null=True),
        ),
    ]
