# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170102_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='dte',
        ),
        migrations.AddField(
            model_name='log',
            name='counter',
            field=models.IntegerField(null=True),
        ),
    ]
