# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_app', '0004_auto_20170102_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfchamp',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bfchamp',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bfchamp',
            name='sport',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betfair_app.BFChamp'),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='pid1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='betfair_app.BFPlayer'),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='pid2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='betfair_app.BFPlayer'),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='rid1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bfevent',
            name='rid2',
            field=models.IntegerField(null=True),
        ),
    ]
