# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_app', '0006_auto_20170102_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bfodds',
            name='ip',
            field=models.NullBooleanField(),
        ),
    ]
